import psycopg2
import json
from app.database.db import get_connection

destinations = [
    {
        "name": "Eden Nature Park & Resort",
        "description": "Lush mountain resort at the foot of Mount Apo featuring pine forests, organic vegetable gardens, adventure sky-rides, and clear gulf vistas.",
        "district": "Davao City",
        "location": "Toril, Davao City",
        "lat": 7.0058,
        "lng": 125.4300,
        "estimated_cost": 1200.00,
        "rating": 4.8,
        "vibes": "nature,relaxing,family,chill,cool",
        "category": "nature,adventure",
        "image_url": "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80",
        "entrance_fee": "₱150 per person",
        "overnight_fee": "₱500 additional fee for overnight campers",
        "operating_hours": "Mondays - Saturdays 8:00 AM - 5:00 PM\nSundays 8:00 AM - 12:00 NN",
        "activities": json.dumps(["Hiking", "Ziplining", "Bird Watching", "Photography", "Fishing"]),
        "activity_prices": json.dumps([
            {"name": "Zipline", "price": "200", "isPerPerson": True},
            {"name": "Skycycle", "price": "250", "isPerPerson": True},
            {"name": "Fishing", "price": "150", "isPerPerson": False}
        ]),
        "accommodations": json.dumps([
            {"type": "Standard Room", "price": "3500", "description": "Cozy room for 2 with breakfast."},
            {"type": "Deluxe Room", "price": "4500", "description": "Spacious room with mountain view."}
        ]),
        "meal_inclusions": "Restaurant available with local and international cuisine",
        "travel_notes": "Best visited early morning. Bring sunscreen and comfortable shoes.",
        "best_time_to_visit": "November to May (dry season). Avoid June to October.",
        "how_to_get_there": "From Davao City: Take a jeepney or taxi to Toril (45-60 mins). Then hire a habal-habal to the park entrance.",
        "estimated_travel_time": "45-60 minutes from Davao City proper",
        "what_to_bring": json.dumps(["Comfortable walking shoes", "Light jacket", "Sunscreen", "Cash"]),
        "meal_plan_details": "Restaurant available on-site serving local and international cuisine. Expect ₱150-₱400 per meal. No outside food allowed.",
        "is_kid_friendly": True,
        "is_wheelchair_accessible": False,
        "is_pet_friendly": False,
        "is_elderly_friendly": True
    },
    {
        "name": "Philippine Eagle Center",
        "description": "Crucial breeding and conservation facility nestled in a rainforest biome dedicated to the endangered Philippine Eagle.",
        "district": "Davao City",
        "location": "Malagos, Calinan, Davao City",
        "lat": 7.2333,
        "lng": 125.3667,
        "estimated_cost": 600.00,
        "rating": 4.6,
        "vibes": "family,nature,educational,adventure,birds",
        "category": "culture,nature",
        "image_url": "https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&q=80",
        "entrance_fee": "₱100 per person",
        "overnight_fee": "Overnight use not available",
        "operating_hours": "8:00 AM - 4:00 PM",
        "activities": json.dumps(["Bird Watching", "Educational Tours", "Photography", "Nature Walks"]),
        "activity_prices": json.dumps([]),
        "accommodations": json.dumps([]),
        "meal_inclusions": "Snack bar available on-site",
        "travel_notes": "Open daily 8AM-4PM. Cool weather, bring light jacket.",
        "best_time_to_visit": "Year-round. Best early morning 8AM-10AM to see eagles active.",
        "how_to_get_there": "From Davao City: Take a jeepney or taxi to Calinan (40-50 mins). Then hire habal-habal to the center.",
        "estimated_travel_time": "45-60 minutes from Davao City proper",
        "what_to_bring": json.dumps(["Light jacket", "Comfortable walking shoes", "Camera", "Cash"]),
        "meal_plan_details": "Snack bar available with light meals and drinks. Expect ₱50-₱200 per item.",
        "is_kid_friendly": True,
        "is_wheelchair_accessible": True,
        "is_pet_friendly": False,
        "is_elderly_friendly": True
    },
    {
        "name": "Malagos Garden Resort",
        "description": "An interactive 12-hectare agricultural eco-resort hosting the country's first interactive chocolate museum, butterfly dome, and bird feeds.",
        "district": "Davao City",
        "location": "Calinan, Davao City",
        "lat": 7.2500,
        "lng": 125.3833,
        "estimated_cost": 1200.00,
        "rating": 4.7,
        "vibes": "nature,family,educational,food,chill",
        "category": "culture,nature",
        "image_url": "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&q=80",
        "entrance_fee": "₱350-₱550 (packages available)",
        "overnight_fee": "₱1,200 for overnight use of facilities",
        "operating_hours": "Mondays - Saturdays 8:00 AM - 5:00 PM\nSundays 8:00 AM - 12:00 NN",
        "activities": json.dumps(["Butterfly Watching", "Bird Feeding", "Chocolate Making", "Swimming", "Horseback Riding"]),
        "activity_prices": json.dumps([
            {"name": "Chocolate Making", "price": "450", "isPerPerson": True},
            {"name": "Bird Feeding", "price": "100", "isPerPerson": True},
            {"name": "Horseback Riding", "price": "350", "isPerPerson": True}
        ]),
        "accommodations": json.dumps([
            {"type": "Deluxe Room", "price": "4200", "description": "Comfortable stay with garden view."},
            {"type": "Executive Suite", "price": "6800", "description": "Luxury suite with premium amenities."}
        ]),
        "meal_inclusions": "On-site restaurant with buffet options",
        "travel_notes": "Perfect for families. Book chocolate museum tour in advance.",
        "best_time_to_visit": "Year-round. Avoid peak holidays as it gets very crowded.",
        "how_to_get_there": "From Davao City: Take a jeepney or taxi to Calinan district (40-50 mins). accessible by private vehicle or habal-habal.",
        "estimated_travel_time": "40-50 minutes from Davao City proper",
        "what_to_bring": json.dumps(["Comfortable walking shoes", "Sunscreen", "Camera", "Extra clothes"]),
        "meal_plan_details": "Full restaurant on-site with buffet options ₱450-₱600/person. Chocolate museum cafe available.",
        "is_kid_friendly": True,
        "is_wheelchair_accessible": True,
        "is_pet_friendly": False,
        "is_elderly_friendly": True
    },
    {
        "name": "Jack's Ridge Resort & Restaurant",
        "description": "Hilltop leisure development situated on a historic WWII Japanese fortress offering panoramic evening views of the city skyline.",
        "district": "Davao City",
        "location": "Shrine Hills, Matina, Davao City",
        "lat": 7.0544,
        "lng": 125.5786,
        "estimated_cost": 800.00,
        "rating": 4.5,
        "vibes": "urban,food,sightseeing,historic,nightlife",
        "category": "urban,culture",
        "image_url": "placeholder",
        "entrance_fee": "Free admission",
        "overnight_fee": "N/A",
        "operating_hours": "10:00 AM - 11:00 PM",
        "activities": json.dumps(["Sightseeing", "Swimming Pool Use", "Dining", "Photography"]),
        "activity_prices": json.dumps([
            {"name": "Swimming Pool Use", "price": "100", "isPerPerson": True}
        ]),
        "accommodations": json.dumps([]),
        "meal_inclusions": "Several restaurants and cafes offering local and international food",
        "travel_notes": "WWII site with historic significance. Excellent sunset views.",
        "best_time_to_visit": "Late afternoon to evening for city lights views.",
        "how_to_get_there": "From Davao City proper: Take a taxi or jeepney passing through Matina, then tricycle up Shrine Hills.",
        "estimated_travel_time": "15-20 minutes from downtown Davao City",
        "what_to_bring": json.dumps(["Camera", "Cash/Card", "Light jacket"]),
        "meal_plan_details": "Vibrant dining options. Budget ₱250-₱600 per meal.",
        "is_kid_friendly": True,
        "is_wheelchair_accessible": True,
        "is_pet_friendly": False,
        "is_elderly_friendly": True
    },
    {
        "name": "People's Park",
        "description": "A vibrant public park in downtown showcasing detailed, giant heritage sculptures by artist Kublai Millan amidst tropical flora.",
        "district": "Davao City",
        "location": "Downtown, Davao City",
        "lat": 7.0722,
        "lng": 125.6083,
        "estimated_cost": 100.00,
        "rating": 4.5,
        "vibes": "urban,relaxing,park,culture,family,free",
        "category": "urban,nature",
        "image_url": "placeholder",
        "entrance_fee": "Free",
        "overnight_fee": "N/A",
        "operating_hours": "5:00 AM - 9:00 PM",
        "activities": json.dumps(["Jogging", "Strolling", "Photography", "Children's Playground"]),
        "activity_prices": json.dumps([]),
        "accommodations": json.dumps([]),
        "meal_inclusions": "Street food stalls and vendors around park perimeter",
        "travel_notes": "Maintained meticulously. Baggage checking is done at entrance.",
        "best_time_to_visit": "Early morning or late afternoon when weather is cooler.",
        "how_to_get_there": "Located at center of Davao City, easily accessible by walking, jeepney, or taxi.",
        "estimated_travel_time": "5-10 minutes from city center",
        "what_to_bring": json.dumps(["Comfortable shoes", "Water bottle", "Camera"]),
        "meal_plan_details": "Outside snacks are allowed. Trash bins are located throughout.",
        "is_kid_friendly": True,
        "is_wheelchair_accessible": True,
        "is_pet_friendly": False,
        "is_elderly_friendly": True
    },
    {
        "name": "Roxas Night Market",
        "description": "A bustling nocturnal culinary and shopping strip in the city core featuring affordable local street food, dynamic vendors, and open massage stalls.",
        "district": "Davao City",
        "location": "Roxas Avenue, Davao City",
        "lat": 7.0706,
        "lng": 125.6128,
        "estimated_cost": 300.00,
        "rating": 4.6,
        "vibes": "urban,food,shopping,nightlife,local",
        "category": "urban,food",
        "image_url": "placeholder",
        "entrance_fee": "Free",
        "overnight_fee": "N/A",
        "operating_hours": "6:00 PM - 12:00 AM",
        "activities": json.dumps(["Street Food Tasting", "Massage Services", "Thrift Shopping"]),
        "activity_prices": json.dumps([
            {"name": "Traditional Massage", "price": "150", "isPerPerson": True}
        ]),
        "accommodations": json.dumps([]),
        "meal_inclusions": "Massive open-air street food stalls",
        "travel_notes": "Very crowded. Watch your belongings closely. Security checks at entry.",
        "best_time_to_visit": "7:00 PM - 9:30 PM for fresh food choices.",
        "how_to_get_there": "Walk or take a jeepney or taxi to Roxas Avenue. Next to Ateneo de Davao.",
        "estimated_travel_time": "5-10 minutes from downtown",
        "what_to_bring": json.dumps(["Cash (small bills)", "Hand sanitizer", "Shopping bag"]),
        "meal_plan_details": "Fabulous grilled foods, ice cream, durian. Budget ₱100-₱250 for a full meal.",
        "is_kid_friendly": True,
        "is_wheelchair_accessible": True,
        "is_pet_friendly": False,
        "is_elderly_friendly": True
    },
    {
        "name": "Davao Crocodile Park & Zoo",
        "description": "Conservation zoo displaying large saltwater and freshwater crocodiles, raptors, exotic reptiles, and educational wildlife lectures.",
        "district": "Davao City",
        "location": "Riverfront Corporate City, Ma-a, Davao City",
        "lat": 7.0983,
        "lng": 125.5978,
        "estimated_cost": 600.00,
        "rating": 4.4,
        "vibes": "family,nature,educational,adventure",
        "category": "nature,wildlife",
        "image_url": "placeholder",
        "entrance_fee": "₱350 per adult, ₱250 per child",
        "overnight_fee": "N/A",
        "operating_hours": "8:00 AM - 5:00 PM",
        "activities": json.dumps(["Crocodile Viewing", "Bird & Raptor Show", "Reptile Handling", "Butterfly Sanctuary"]),
        "activity_prices": json.dumps([]),
        "accommodations": json.dumps([]),
        "meal_inclusions": "Kaonanan Restaurant and ice cream parlour available",
        "travel_notes": "Try the Crocodile Durian Ice Cream. Highly recommended for kids.",
        "best_time_to_visit": "Weekends to watch live animal shows.",
        "how_to_get_there": "Take a taxi directly to Riverfront Corporate City in Ma-a.",
        "estimated_travel_time": "20-30 minutes from downtown",
        "what_to_bring": json.dumps(["Sunscreen", "Cap/Umbrella", "Camera", "Cash"]),
        "meal_plan_details": "Civet coffee and exotic crocodile dishes available at the restaurant. Budget ₱200-₱500.",
        "is_kid_friendly": True,
        "is_wheelchair_accessible": True,
        "is_pet_friendly": False,
        "is_elderly_friendly": True
    },
    {
        "name": "Pearl Farm Beach Resort",
        "description": "Premium world-class private island hideaway featuring iconic over-water stilt bungalows, infinity pools, and marine sanctuaries.",
        "district": "Davao del Norte",
        "location": "Samal Island, Davao del Norte",
        "lat": 7.1065,
        "lng": 125.6888,
        "estimated_cost": 12000.00,
        "rating": 4.9,
        "vibes": "beach,luxury,relaxing,romantic,chill",
        "category": "beach,resort",
        "image_url": "placeholder",
        "entrance_fee": "₱3,500 day tour (includes boat transfer & buffet lunch)",
        "overnight_fee": "Included in room rates",
        "operating_hours": "24 hours",
        "activities": json.dumps(["Diving", "Spa Sessions", "Snorkeling", "Kayaking", "Jet Skiing"]),
        "activity_prices": json.dumps([
            {"name": "Scuba Diving Guide", "price": "1500", "isPerPerson": True}
        ]),
        "accommodations": json.dumps([
            {"type": "Hilltop Room", "price": "9500", "description": "Overlooking the gardens and sea."},
            {"type": "Samal House", "price": "14500", "description": "Stilt house over the gulf water."}
        ]),
        "meal_inclusions": "Buffet dining at Maranao Restaurant",
        "travel_notes": "Luxury destination. Strictly enforce conservation guidelines.",
        "best_time_to_visit": "December to May for calm blue seas.",
        "how_to_get_there": "Take private boat transfer from Pearl Farm Marina Wharf in Lanang, Davao City.",
        "estimated_travel_time": "45 minutes boat ride from Marina Wharf",
        "what_to_bring": json.dumps(["Elegant swimwear", "Reef-safe sunscreen", "Credit card/Cash"]),
        "meal_plan_details": "World-class seafood buffet and tropical cocktails at the beachside bars.",
        "is_kid_friendly": True,
        "is_wheelchair_accessible": False,
        "is_pet_friendly": False,
        "is_elderly_friendly": True
    },
    {
        "name": "Hagimit Falls",
        "description": "Multi-layered woodland cascade flowing into wide natural limestone wading pools shaded by pristine jungle vegetation.",
        "district": "Davao del Norte",
        "location": "Babak District, Samal Island, Davao del Norte",
        "lat": 7.0869,
        "lng": 125.7066,
        "estimated_cost": 500.00,
        "rating": 4.6,
        "vibes": "nature,relaxing,waterfalls,family,chill",
        "category": "nature,waterfalls",
        "image_url": "placeholder",
        "entrance_fee": "₱40 per person",
        "overnight_fee": "₱150 tent space fee",
        "operating_hours": "6:00 AM - 6:00 PM",
        "activities": json.dumps(["Swimming", "Waterfall Wading", "Camping", "Picnicking"]),
        "activity_prices": json.dumps([
            {"name": "Cottage Rental", "price": "300", "isPerPerson": False}
        ]),
        "accommodations": json.dumps([
            {"type": "Wooden Cabin", "price": "1200", "description": "Basic fan cabin near falls."}
        ]),
        "meal_inclusions": "Bring your own packed meals. Grill zones available.",
        "travel_notes": "Paths can be slippery. Be careful with kids.",
        "best_time_to_visit": "December to May. Water is clear and green.",
        "how_to_get_there": "From Samal Wharf: Hire a tricycle or habal-habal directly to Hagimit.",
        "estimated_travel_time": "20 minutes from Babak Wharf",
        "what_to_bring": json.dumps(["Aqua shoes", "Towel", "Waterproof bag", "Dry clothes"]),
        "meal_plan_details": "Small sari-sari stores sell instant noodles and sodas. Best to bring your own food.",
        "is_kid_friendly": True,
        "is_wheelchair_accessible": False,
        "is_pet_friendly": False,
        "is_elderly_friendly": False
    },
    {
        "name": "Isla Reta Beach",
        "description": "Idyllic beachfront showcasing a wide shoreline of fine white sand, towering Talisay trees, and deep clear tropical waters.",
        "district": "Davao del Norte",
        "location": "Talicud Island, Samal, Davao del Norte",
        "lat": 6.9806,
        "lng": 125.6881,
        "estimated_cost": 900.00,
        "rating": 4.7,
        "vibes": "beach,snorkeling,camping,nature,chill",
        "category": "beach,camping",
        "image_url": "placeholder",
        "entrance_fee": "₱100 day tour, ₱200 overnight",
        "overnight_fee": "Included in overnight entry fee",
        "operating_hours": "24 hours",
        "activities": json.dumps(["Beach Swimming", "Snorkeling", "Camping", "Island Hopping"]),
        "activity_prices": json.dumps([
            {"name": "Tent Rental", "price": "400", "isPerPerson": False}
        ]),
        "accommodations": json.dumps([
            {"type": "Standard Cottage", "price": "1000", "description": "Open-air cottage near beach."},
            {"type": "AC Concrete Room", "price": "2500", "description": "Comfortable room with private bath."}
        ]),
        "meal_inclusions": "Restaurant serving fresh fish and local dishes",
        "travel_notes": "Very clean beach shaded by native Talisay trees. Electric power limited at night.",
        "best_time_to_visit": "December to May for clear seas.",
        "how_to_get_there": "Take a passenger boat from Santa Ana Wharf in Davao City directly to Talicud Island.",
        "estimated_travel_time": "1 hour boat ride from Santa Ana Wharf",
        "what_to_bring": json.dumps(["Swimwear", "Snorkel gear", "Power bank", "Cash only"]),
        "meal_plan_details": "Resort restaurant available. Cooking and grilling permitted in open zones.",
        "is_kid_friendly": True,
        "is_wheelchair_accessible": False,
        "is_pet_friendly": False,
        "is_elderly_friendly": False
    },
    {
        "name": "Monfort Bat Sanctuary",
        "description": "Protected cave property housing millions of Rousette fruit bats, recognized globally by the Guinness World Records.",
        "district": "Davao del Norte",
        "location": "Babak, Samal Island, Davao del Norte",
        "lat": 7.1333,
        "lng": 125.6500,
        "estimated_cost": 300.00,
        "rating": 4.5,
        "vibes": "nature,educational,conservation,bats",
        "category": "nature,conservation",
        "image_url": "placeholder",
        "entrance_fee": "₱120 per person",
        "overnight_fee": "N/A",
        "operating_hours": "8:00 AM - 5:00 PM",
        "activities": json.dumps(["Cave Bat Viewing", "Eco-trail Walking", "Souvenir Shopping"]),
        "activity_prices": json.dumps([]),
        "accommodations": json.dumps([]),
        "meal_inclusions": "No food served on site",
        "travel_notes": "Guinness World Record for largest fruit bat colony. Do not use camera flash.",
        "best_time_to_visit": "Late afternoon near sunset to see bats active.",
        "how_to_get_there": "From Babak Wharf: Take a tricycle or motorcycle directly to the sanctuary.",
        "estimated_travel_time": "10-15 minutes from Babak Wharf",
        "what_to_bring": json.dumps(["Cap/Hat", "Camera (no flash)", "Water bottle", "Cash"]),
        "meal_plan_details": "No restaurant. Snacks available at entry gate.",
        "is_kid_friendly": True,
        "is_wheelchair_accessible": False,
        "is_pet_friendly": False,
        "is_elderly_friendly": True
    },
    {
        "name": "Mount Apo National Park",
        "description": "High-altitude wilderness reserve guarding the highest peak in the Philippines, marked by volcanic rocks and mossy cloud forests.",
        "district": "Davao del Sur",
        "location": "Kapatagan, Digos City, Davao del Sur",
        "lat": 6.9875,
        "lng": 125.2708,
        "estimated_cost": 5000.00,
        "rating": 4.9,
        "vibes": "nature,adventure,hiking,mountain",
        "category": "nature,mountain",
        "image_url": "placeholder",
        "entrance_fee": "₱2,000 Special Permit Fee",
        "overnight_fee": "Included in permit fee for designated campsites",
        "operating_hours": "24 hours",
        "activities": json.dumps(["Highland Mountain Trekking", "Alpine Camping", "Wildlife Sightseeing"]),
        "activity_prices": json.dumps([
            {"name": "Mandatory Guide (Daily)", "price": "1500", "isPerPerson": False},
            {"name": "Mountain Porter (Daily)", "price": "800", "isPerPerson": False}
        ]),
        "accommodations": json.dumps([
            {"type": "Camping Ground", "price": "0", "description": "Designated mountain campsite slots."}
        ]),
        "meal_inclusions": "Bring your own freeze-dried food and cooking equipment",
        "travel_notes": "Requires physical conditioning and medical clearance certificate.",
        "best_time_to_visit": "March to May (dry season). Summit views are best.",
        "how_to_get_there": "Register at LGU Digos, hire a 4x4 or take a van to Kapatagan base camp.",
        "estimated_travel_time": "2-3 hours from Davao City to Kapatagan",
        "what_to_bring": json.dumps(["Cold-climate sleeping bag", "Water filter", "Medical kit", "Warm layers"]),
        "meal_plan_details": "Self-cooking is required. Portable gas stoves recommended. Leave No Trace policy strictly enforced.",
        "is_kid_friendly": False,
        "is_wheelchair_accessible": False,
        "is_pet_friendly": False,
        "is_elderly_friendly": False
    },
    {
        "name": "Kapatagan Valley (Kublai Art Garden)",
        "description": "Cool highland basin displaying massive outdoor structural monuments, pine trails, and organic arabica coffee farms.",
        "district": "Davao del Sur",
        "location": "Kapatagan, Digos City, Davao del Sur",
        "lat": 6.8524,
        "lng": 125.3211,
        "estimated_cost": 800.00,
        "rating": 4.6,
        "vibes": "art,highland,sculptures,coffee,culture",
        "category": "culture,highland",
        "image_url": "placeholder",
        "entrance_fee": "₱100 per person",
        "overnight_fee": "Included in cabin packages",
        "operating_hours": "8:00 AM - 5:00 PM",
        "activities": json.dumps(["Art Walk", "Agong House Tour", "Highland Coffee Tasting", "Photography"]),
        "activity_prices": json.dumps([
            {"name": "Agong House Tour Guide", "price": "150", "isPerPerson": True}
        ]),
        "accommodations": json.dumps([
            {"type": "Pine Cabin", "price": "2200", "description": "Highland cabin with pine wood walls."}
        ]),
        "meal_inclusions": "Cafeteria serves Mt. Apo Arabica coffee and native meals",
        "travel_notes": "Perfect escape from city heat. Very cool and foggy.",
        "best_time_to_visit": "December to May. Beautiful mountain vistas.",
        "how_to_get_there": "Take a bus from Davao to Digos City, then hire a local van to Kapatagan.",
        "estimated_travel_time": "2 hours from Davao City",
        "what_to_bring": json.dumps(["Sweater", "Camera", "Cash/GCash", "Comfortable shoes"]),
        "meal_plan_details": "Taste Mt. Apo specialty coffee and local highland vegetables. Budget ₱150-₱350.",
        "is_kid_friendly": True,
        "is_wheelchair_accessible": False,
        "is_pet_friendly": False,
        "is_elderly_friendly": True
    },
    {
        "name": "Passig Islet",
        "description": "Unique circular sandbar islet enclosed by seagrass flats offering crystal-clear swimming channels.",
        "district": "Davao del Sur",
        "location": "Bato, Santa Cruz, Davao del Sur",
        "lat": 6.8791,
        "lng": 125.4542,
        "estimated_cost": 400.00,
        "rating": 4.4,
        "vibes": "sandbar,beach,swimming,islet,picnic",
        "category": "beach,island",
        "image_url": "placeholder",
        "entrance_fee": "₱25 per person",
        "overnight_fee": "Overnight stay is not permitted",
        "operating_hours": "6:00 AM - 6:00 PM",
        "activities": json.dumps(["Seawater Wading", "Beach Volleyball", "Bridges Strolling", "Picnicking"]),
        "activity_prices": json.dumps([
            {"name": "Boat Ride Roundtrip", "price": "50", "isPerPerson": True},
            {"name": "Cottage Rental", "price": "250", "isPerPerson": False}
        ]),
        "accommodations": json.dumps([]),
        "meal_inclusions": "Grill stations and small food stalls on-site",
        "travel_notes": "Unique man-made sandbar islet. Eco-park with concrete walk-bridges.",
        "best_time_to_visit": "December to May. Swimming is best during high tide.",
        "how_to_get_there": "From Davao City: Take a bus to Santa Cruz, drop off at Brgy. Bato, then take tricycle to wharf.",
        "estimated_travel_time": "1.5 hours from Davao City",
        "what_to_bring": json.dumps(["Swimwear", "Sunscreen", "Towel", "Cash only"]),
        "meal_plan_details": "Bring packed lunch and raw food for grilling. Limited options on the islet.",
        "is_kid_friendly": True,
        "is_wheelchair_accessible": False,
        "is_pet_friendly": False,
        "is_elderly_friendly": False
    },
    {
        "name": "Dahican Beach",
        "description": "Stunning 7-kilometer crescent of open white sand facing deep Pacific swells, famous for world-class skimboarding and turtle nesting.",
        "district": "Davao Oriental",
        "location": "Mati, Davao Oriental",
        "lat": 6.9272,
        "lng": 126.3023,
        "estimated_cost": 1500.00,
        "rating": 4.8,
        "vibes": "beach,adventure,surfing,nature,relaxing",
        "category": "beach,surfing",
        "image_url": "placeholder",
        "entrance_fee": "₱20 per person",
        "overnight_fee": "₱200 tent space fee",
        "operating_hours": "24 hours",
        "activities": json.dumps(["Surfing", "Skimboarding", "Sea Turtle Spotting", "Camping", "Swimming"]),
        "activity_prices": json.dumps([
            {"name": "Skimboard Rental (Hour)", "price": "100", "isPerPerson": True},
            {"name": "Surf Lesson with Coach (Hour)", "price": "400", "isPerPerson": True}
        ]),
        "accommodations": json.dumps([
            {"type": "Surf Hut", "price": "1200", "description": "Simple beachfront bamboo hut."},
            {"type": "Standard AC Room", "price": "2800", "description": "Comfortable room for 2."}
        ]),
        "meal_inclusions": "Beachfront cafes serving local seafood",
        "travel_notes": "World-class skimboarding. Strong waves from October to March.",
        "best_time_to_visit": "October to March for optimal surfing waves.",
        "how_to_get_there": "Take a bus or van from Davao City to Mati City, then hire a tricycle to Dahican.",
        "estimated_travel_time": "3-4 hours from Davao City",
        "what_to_bring": json.dumps(["Swimwear", "Reef-safe sunscreen", "Cash", "Towel"]),
        "meal_plan_details": "Fresh seafood and grilled fish are specialties. Budget ₱150-₱350 per meal.",
        "is_kid_friendly": True,
        "is_wheelchair_accessible": False,
        "is_pet_friendly": True,
        "is_elderly_friendly": False
    },
    {
        "name": "Sleeping Dinosaur Island Viewdeck",
        "description": "Panoramic highway rest-stop viewpoint showcasing a mountain peninsula perfectly resembling a giant resting dinosaur dipping into the bay.",
        "district": "Davao Oriental",
        "location": "Mati, Davao Oriental",
        "lat": 6.8533,
        "lng": 126.2300,
        "estimated_cost": 200.00,
        "rating": 4.7,
        "vibes": "nature,sightseeing,adventure,romantic,quick_stop",
        "category": "nature,viewpoint",
        "image_url": "placeholder",
        "entrance_fee": "₱10 per person",
        "overnight_fee": "N/A",
        "operating_hours": "24 hours",
        "activities": json.dumps(["Observation Deck Sightseeing", "Photography", "Souvenir Shopping"]),
        "activity_prices": json.dumps([]),
        "accommodations": json.dumps([]),
        "meal_inclusions": "Snack stalls and small food shops at the viewdeck base",
        "travel_notes": "Perfect short roadtrip stop. Island peninsula shaped like a sleeping dinosaur.",
        "best_time_to_visit": "Early morning or late afternoon for golden hour photos.",
        "how_to_get_there": "Take a bus or private car from Davao City heading to Mati. Viewdeck is along highway.",
        "estimated_travel_time": "3 hours from Davao City",
        "what_to_bring": json.dumps(["Camera/Phone", "Sunglasses", "Cash", "Sunscreen"]),
        "meal_plan_details": "Try local empanadas and coconut juice. Budget ₱50-₱150.",
        "is_kid_friendly": True,
        "is_wheelchair_accessible": True,
        "is_pet_friendly": True,
        "is_elderly_friendly": True
    },
    {
        "name": "Aliwagwag Falls Ecopark",
        "description": "Scenic multi-tiered rock cascade featuring 84 clean tiers flowing down through a massive protected tropical canopy.",
        "district": "Davao Oriental",
        "location": "Cateel, Davao Oriental",
        "lat": 7.7342,
        "lng": 126.2947,
        "estimated_cost": 800.00,
        "rating": 4.8,
        "vibes": "nature,waterfalls,sightseeing,adventure",
        "category": "nature,waterfalls",
        "image_url": "placeholder",
        "entrance_fee": "₱100 per adult, ₱50 per child",
        "overnight_fee": "No camping inside falls property",
        "operating_hours": "8:00 AM - 5:00 PM",
        "activities": json.dumps(["Canopy Zipline", "Monkey Bridge Crossing", "Waterfall Wading", "Eco-hiking"]),
        "activity_prices": json.dumps([
            {"name": "Zipline", "price": "200", "isPerPerson": True},
            {"name": "Monkey Bridge", "price": "50", "isPerPerson": True}
        ]),
        "accommodations": json.dumps([]),
        "meal_inclusions": "Rest area serves quick native dishes",
        "travel_notes": "84-tiered pristine waterfall. Highest cascading waterfall in the Philippines.",
        "best_time_to_visit": "December to May when river waters are clear and clean.",
        "how_to_get_there": "Take a bus from Davao City directly to Cateel, then tricycle to the eco-park.",
        "estimated_travel_time": "5-6 hours from Davao City",
        "what_to_bring": json.dumps(["Change of clothes", "Trekking sandals", "Waterproof bag", "Cash"]),
        "meal_plan_details": "Local rice meals and native snacks available. Budget ₱100-₱250.",
        "is_kid_friendly": True,
        "is_wheelchair_accessible": False,
        "is_pet_friendly": False,
        "is_elderly_friendly": True
    },
    {
        "name": "Mount Hamiguitan Wildlife Sanctuary",
        "description": "Highly restricted mountain nature park hosting a vast centuries-old pygmy bonsai forest and rich, vulnerable flora and fauna.",
        "district": "Davao Oriental",
        "location": "San Isidro, Davao Oriental",
        "lat": 6.7264,
        "lng": 126.1833,
        "estimated_cost": 3000.00,
        "rating": 4.8,
        "vibes": "nature,adventure,hiking,unesco,mountain",
        "category": "nature,hiking",
        "image_url": "placeholder",
        "entrance_fee": "₱50 museum entry fee, ₱500 trekking permit fee",
        "overnight_fee": "Included in trekking registration packages",
        "operating_hours": "8:00 AM - 4:00 PM",
        "activities": json.dumps(["High-Altitude Trekking", "Bonsai Forest Viewing", "Wildlife Museum Visit", "Eco-learning"]),
        "activity_prices": json.dumps([
            {"name": "Mandatory Guide (Daily)", "price": "1000", "isPerPerson": False}
        ]),
        "accommodations": json.dumps([
            {"type": "Mountain Campsite", "price": "0", "description": "Trekking base camp slots."}
        ]),
        "meal_inclusions": "Bring your own rations for the climb",
        "travel_notes": "UNESCO World Heritage Site. Rich biodiversity. Extremely strict environmental protocols.",
        "best_time_to_visit": "March to May (dry season for climbing).",
        "how_to_get_there": "From Davao City: Take a bus to San Isidro, register at Hamiguitan Visitor Center.",
        "estimated_travel_time": "3.5 hours from Davao City",
        "what_to_bring": json.dumps(["Trekking gear", "Thermal clothing", "Raincoat", "First aid kit"]),
        "meal_plan_details": "Self-cooking required on trails. Food at visitor center is budget-friendly.",
        "is_kid_friendly": False,
        "is_wheelchair_accessible": False,
        "is_pet_friendly": False,
        "is_elderly_friendly": False
    },
    {
        "name": "Cape San Agustin",
        "description": "Dramatic ocean cliffside marked by three distinct towering historic lighthouses where the Davao Gulf collides with the Pacific.",
        "district": "Davao Oriental",
        "location": "Governor Generoso, Davao Oriental",
        "lat": 6.2736,
        "lng": 126.1917,
        "estimated_cost": 2000.00,
        "rating": 4.7,
        "vibes": "nature,adventure,sightseeing,historic,romantic",
        "category": "nature,landmark",
        "image_url": "placeholder",
        "entrance_fee": "Free",
        "overnight_fee": "Campsites available at nearby resorts",
        "operating_hours": "24 hours",
        "activities": json.dumps(["Lighthouse Climbing", "Coastal Cliff Walk", "Sunset Worshipping", "Photography"]),
        "activity_prices": json.dumps([
            {"name": "Local Tour Guide", "price": "200", "isPerPerson": False}
        ]),
        "accommodations": json.dumps([]),
        "meal_inclusions": "No food sold inside lighthouse compound",
        "travel_notes": "Stunning spot where Pacific meets Davao Gulf. Features three historic lighthouses.",
        "best_time_to_visit": "December to May for safe dry roads.",
        "how_to_get_there": "Take bus to Tagum or Mati, then van to Governor Generoso, hire local tricycle.",
        "estimated_travel_time": "4-5 hours from Davao City",
        "what_to_bring": json.dumps(["Umbrella/Hat", "Trekking sandals", "Camera", "Plenty of water"]),
        "meal_plan_details": "Best to bring packed lunch. Nearest local eateries are in town center (30 mins away).",
        "is_kid_friendly": True,
        "is_wheelchair_accessible": False,
        "is_pet_friendly": True,
        "is_elderly_friendly": False
    },
    {
        "name": "Lake Carolina",
        "description": "Quiet, brackish forest lagoon surrounded by mature trees, famous for extremely transparent green-turquoise tidal waters.",
        "district": "Davao Oriental",
        "location": "Baganga, Davao Oriental",
        "lat": 7.5684,
        "lng": 126.5411,
        "estimated_cost": 600.00,
        "rating": 4.6,
        "vibes": "lake,lagoon,swimming,rafting,nature",
        "category": "nature,lake",
        "image_url": "placeholder",
        "entrance_fee": "₱30 per person",
        "overnight_fee": "N/A",
        "operating_hours": "6:00 AM - 6:00 PM",
        "activities": json.dumps(["Lagoon Wading", "Bamboo Rafting", "Photography", "Picnicking"]),
        "activity_prices": json.dumps([
            {"name": "Bamboo Raft Rental", "price": "150", "isPerPerson": False},
            {"name": "Cottage Rental", "price": "250", "isPerPerson": False}
        ]),
        "accommodations": json.dumps([]),
        "meal_inclusions": "Bring your own packed meals. Fresh coconut sold nearby.",
        "travel_notes": "Astonishingly clear brackish lagoon with turquoise waters.",
        "best_time_to_visit": "December to May. High tide makes wading magical.",
        "how_to_get_there": "Take a bus from Tagum City or Davao City heading to Baganga, drop off at Carolina junction.",
        "estimated_travel_time": "4.5 hours from Davao City",
        "what_to_bring": json.dumps(["Swimwear", "Towel", "Cash only", "Sunscreen"]),
        "meal_plan_details": "No proper restaurants on-site. Pack a picnic lunch. Budget ₱100-₱200.",
        "is_kid_friendly": True,
        "is_wheelchair_accessible": False,
        "is_pet_friendly": False,
        "is_elderly_friendly": True
    },
    {
        "name": "San Victor Island",
        "description": "A secluded 3-hectare coconut islet boasting fine white sandbanks and hyper-clear surrounding coral reefs.",
        "district": "Davao Oriental",
        "location": "Baganga, Davao Oriental",
        "lat": 7.5256,
        "lng": 126.5819,
        "estimated_cost": 1000.00,
        "rating": 4.6,
        "vibes": "beach,nature,relaxing,island,quiet",
        "category": "beach,island",
        "image_url": "placeholder",
        "entrance_fee": "₱100 day tour roundtrip, ₱150 overnight roundtrip",
        "overnight_fee": "₱150 tent space fee",
        "operating_hours": "24 hours",
        "activities": json.dumps(["Coral Snorkeling", "Beach Swimming", "Marine Sanctuary Trekking", "Camping"]),
        "activity_prices": json.dumps([
            {"name": "Cottage Rental", "price": "500", "isPerPerson": False}
        ]),
        "accommodations": json.dumps([
            {"type": "Standard Beach Cottage", "price": "1200", "description": "Basic beachfront accommodation."}
        ]),
        "meal_inclusions": "Local kitchen serves grilled fish and rice on demand",
        "travel_notes": "Serene 3-hectare coconut island off the coast of Baganga.",
        "best_time_to_visit": "December to May for calm blue seas.",
        "how_to_get_there": "From Baganga proper: Hire a tricycle to the boat launch in Brgy. San Victor (15 mins), then 5 mins boat ride.",
        "estimated_travel_time": "4.5 hours from Davao City total",
        "what_to_bring": json.dumps(["Snorkel gear", "Beachwear", "Power bank", "Cash"]),
        "meal_plan_details": "Simple fish grilling service. Best to bring snacks and drinks. Budget ₱150-₱300.",
        "is_kid_friendly": True,
        "is_wheelchair_accessible": False,
        "is_pet_friendly": True,
        "is_elderly_friendly": True
    },
    {
        "name": "Kopiat Island",
        "description": "Lush, uninhabited ring-island protected sanctuary featuring vibrant coral flats and crucial nesting shores for turtles.",
        "district": "Davao de Oro",
        "location": "Mabini, Davao de Oro",
        "lat": 7.3014,
        "lng": 125.8617,
        "estimated_cost": 1800.00,
        "rating": 4.6,
        "vibes": "beach,nature,snorkeling,island,adventure",
        "category": "beach,island",
        "image_url": "placeholder",
        "entrance_fee": "Free",
        "overnight_fee": "Overnight stays not permitted",
        "operating_hours": "6:00 AM - 6:00 PM",
        "activities": json.dumps(["Snorkeling in Coral Gardens", "Turtle Spotting", "Kayaking", "Island Exploring"]),
        "activity_prices": json.dumps([
            {"name": "Roundtrip Boat Transfer", "price": "1500", "isPerPerson": False}
        ]),
        "accommodations": json.dumps([]),
        "meal_inclusions": "No food available. Strictly pack your own meals.",
        "travel_notes": "Uninhabited island sanctuary. Sea turtle nesting grounds. Heavy fines for trash littering.",
        "best_time_to_visit": "December to May for excellent marine visibility.",
        "how_to_get_there": "From Tagum City: Take a bus or multi-cab to Mabini port, then hire a pumpboat.",
        "estimated_travel_time": "1.5 hours from Davao City to Mabini port",
        "what_to_bring": json.dumps(["Snorkel gear", "Plenty of water", "Packed lunch", "Dry bag"]),
        "meal_plan_details": "Zero commercial stalls. Bring all trash back to mainland. Budget ₱150-₱300 for food supplies.",
        "is_kid_friendly": True,
        "is_wheelchair_accessible": False,
        "is_pet_friendly": False,
        "is_elderly_friendly": False
    },
    {
        "name": "Lake Leonard",
        "description": "Serene highland freshwater caldera lake enveloped by deep, primary montane forest, popular for campouts.",
        "district": "Davao de Oro",
        "location": "Maco, Davao de Oro",
        "lat": 7.3828,
        "lng": 126.0494,
        "estimated_cost": 600.00,
        "rating": 4.5,
        "vibes": "nature,relaxing,camping,lake,quiet",
        "category": "nature,lake",
        "image_url": "placeholder",
        "entrance_fee": "₱50 per person",
        "overnight_fee": "₱100 camping space fee",
        "operating_hours": "6:00 AM - 6:00 PM",
        "activities": json.dumps(["Bamboo Rafting", "Alpine Camping", "Trout Fishing", "Bird Watching"]),
        "activity_prices": json.dumps([
            {"name": "Bamboo Rafting", "price": "150", "isPerPerson": False}
        ]),
        "accommodations": json.dumps([
            {"type": "Tent Site", "price": "100", "description": "Designated lakeside camping pitches."}
        ]),
        "meal_inclusions": "Bring your own cooking supplies and food",
        "travel_notes": "Freshwater caldera lake in Maco. Very quiet, clean and tranquil.",
        "best_time_to_visit": "December to May. Ideal for crisp morning fog.",
        "how_to_get_there": "From Tagum City: Hire a habal-habal or take a private 4x4 to Maco caldera.",
        "estimated_travel_time": "2 hours from Davao City",
        "what_to_bring": json.dumps(["Camping tent", "Warm jacket", "Flashlight/Lantern", "Food supplies"]),
        "meal_plan_details": "Self-catering is a must. No restaurants on-site. Local shops at base sell basic snacks.",
        "is_kid_friendly": True,
        "is_wheelchair_accessible": False,
        "is_pet_friendly": True,
        "is_elderly_friendly": True
    },
    {
        "name": "Haven't Peak Highland Resort",
        "description": "Hillside highland resort nestled in cold, cloud-covered mountains offering sweeping sunrise views over the valley.",
        "district": "Davao de Oro",
        "location": "Maragusan, Davao de Oro",
        "lat": 7.3228,
        "lng": 126.1558,
        "estimated_cost": 1500.00,
        "rating": 4.6,
        "vibes": "nature,relaxing,cool,mountain,chill",
        "category": "nature,resort",
        "image_url": "placeholder",
        "entrance_fee": "₱100 per person",
        "overnight_fee": "Included in cabin charges",
        "operating_hours": "24 hours",
        "activities": json.dumps(["Cable Car Wading", "Fog Observing", "Highland Dining", "Pine Strolling"]),
        "activity_prices": json.dumps([
            {"name": "Cable Car", "price": "150", "isPerPerson": True}
        ]),
        "accommodations": json.dumps([
            {"type": "A-Frame Cabin", "price": "1800", "description": "Cozy triangular cabin with valley view."},
            {"type": "Standard AC Villa", "price": "3200", "description": "Modern room with hot shower."}
        ]),
        "meal_inclusions": "Hilltop dining restaurant serving warm soups and native dishes",
        "travel_notes": "Very cool highland climate. Beautiful view of Maragusan valley fog.",
        "best_time_to_visit": "December to May for cool clear dry season nights.",
        "how_to_get_there": "From Davao City: Take a bus or van to Maragusan terminal, then take habal-habal to the resort.",
        "estimated_travel_time": "3.5-4 hours from Davao City",
        "what_to_bring": json.dumps(["Thick sweaters", "Closed walking shoes", "Camera", "Cash/GCash"]),
        "meal_plan_details": "Hilltop dining room features hot soup pots and native pork dishes. Budget ₱200-₱450.",
        "is_kid_friendly": True,
        "is_wheelchair_accessible": False,
        "is_pet_friendly": False,
        "is_elderly_friendly": True
    },
    {
        "name": "Tagbibinta Falls",
        "description": "Dramatic 700-foot multi-tiered waterfall cascading down cool forested mountains.",
        "district": "Davao de Oro",
        "location": "Maragusan, Davao de Oro",
        "lat": 7.3478,
        "lng": 126.1367,
        "estimated_cost": 400.00,
        "rating": 4.5,
        "vibes": "nature,waterfalls,adventure,hiking",
        "category": "nature,waterfalls",
        "image_url": "placeholder",
        "entrance_fee": "₱40 per person",
        "overnight_fee": "No overnight camping allowed inside waterfall area",
        "operating_hours": "6:00 AM - 5:00 PM",
        "activities": json.dumps(["Waterfall Wading", "Mountain Wading Trail Trek", "Photography"]),
        "activity_prices": json.dumps([
            {"name": "Cottage Rental", "price": "250", "isPerPerson": False}
        ]),
        "accommodations": json.dumps([]),
        "meal_inclusions": "Cottages available for packed lunches",
        "travel_notes": "700-foot multi-tiered waterfall cascading down cool forested mountains.",
        "best_time_to_visit": "December to May when water currents are safe and clear.",
        "how_to_get_there": "From Maragusan terminal: Hire local tricycle or habal-habal to Tagbibinta junction.",
        "estimated_travel_time": "15 minutes from Maragusan town proper",
        "what_to_bring": json.dumps(["Aqua shoes", "Towel", "Waterproof dry bag", "Cash only"]),
        "meal_plan_details": "Snack stands sell local delicacies and drinks. Budget ₱50-₱150.",
        "is_kid_friendly": True,
        "is_wheelchair_accessible": False,
        "is_pet_friendly": False,
        "is_elderly_friendly": True
    }
]

def seed():
    conn = None
    cur = None
    try:
        print("Connecting to Neon PostgreSQL database...")
        conn = get_connection()
        cur = conn.cursor()
        
        print("Deleting existing destinations to avoid duplicates...")
        cur.execute("DELETE FROM destinations;")
        
        # Reset serial sequence if it exists so ids start at 1
        try:
            cur.execute("ALTER SEQUENCE destinations_destination_id_seq RESTART WITH 1;")
            print("Reset auto-increment sequence.")
        except Exception:
            conn.rollback()
            cur = conn.cursor()
            print("Sequence reset skipped or failed (not critical).")
            
        print(f"Seeding {len(destinations)} enriched Davao Region destinations...")
        for dest in destinations:
            cur.execute("""
                INSERT INTO destinations (
                    name, description, lat, lng, estimated_cost, vibes, rating,
                    district, image_url, category, location, entrance_fee, overnight_fee,
                    operating_hours, activities, activity_prices, accommodations,
                    meal_inclusions, travel_notes, best_time_to_visit, how_to_get_there,
                    estimated_travel_time, what_to_bring, meal_plan_details,
                    is_kid_friendly, is_wheelchair_accessible, is_pet_friendly, is_elderly_friendly
                )
                VALUES (
                    %s, %s, %s, %s, %s, %s, %s,
                    %s, %s, %s, %s, %s, %s,
                    %s, %s, %s, %s,
                    %s, %s, %s, %s,
                    %s, %s, %s,
                    %s, %s, %s, %s
                );
            """, (
                dest["name"], dest["description"], dest["lat"], dest["lng"], dest["estimated_cost"], dest["vibes"], dest["rating"],
                dest["district"], dest["image_url"], dest["category"], dest["location"], dest["entrance_fee"], dest["overnight_fee"],
                dest["operating_hours"], dest["activities"], dest["activity_prices"], dest["accommodations"],
                dest["meal_inclusions"], dest["travel_notes"], dest["best_time_to_visit"], dest["how_to_get_there"],
                dest["estimated_travel_time"], dest["what_to_bring"], dest["meal_plan_details"],
                dest["is_kid_friendly"], dest["is_wheelchair_accessible"], dest["is_pet_friendly"], dest["is_elderly_friendly"]
            ))
            
        conn.commit()
        print("Successfully seeded all 25 enriched destinations!")
        
    except Exception as e:
        print(f"Error seeding database: {e}")
        if conn:
            conn.rollback()
    finally:
        if cur: cur.close()
        if conn: conn.close()

if __name__ == "__main__":
    seed()
